"""LLM analysis entrypoint.

Intraday-Oi owns deterministic market calculations. LLM generation is delegated
to the shared supaBOT gateway so downstream code does not select Gemini models
or bypass verification/telemetry.
"""

from __future__ import annotations

from typing import Any

try:
    from .supabot_llm import analyze_with_supabot, SupaBOTLLMError
except ImportError:
    from supabot_llm import analyze_with_supabot, SupaBOTLLMError


def summarize_raw_series(raw_series: Any) -> dict[str, Any]:
    """Small compatibility helper for callers/tests that inspect raw series.

    The full deterministic payload is sent through the central adapter. This
    helper intentionally returns only source facts and does not calculate new
    market metrics.
    """
    if not isinstance(raw_series, dict):
        return {"note": "No raw series available"}
    rows = raw_series.get("strike_rows") or []
    totals = raw_series.get("totals") or {}
    gex = raw_series.get("gex") or {}
    return {
        "mode": raw_series.get("mode"),
        "dte": raw_series.get("dte"),
        "totals": totals,
        "gex": {
            "status": gex.get("status"),
            "net_gex": gex.get("net_gex"),
            "gamma_flip": gex.get("gamma_flip"),
            "call_wall": gex.get("call_wall"),
            "put_wall": gex.get("put_wall"),
            "max_abs_gex_strike": gex.get("max_abs_gex_strike"),
        },
        "strike_count": len(rows),
    }


def analyze(parsed: dict[str, Any], history: dict[str, Any] | None = None) -> dict[str, Any]:
    """Return human-readable market analysis generated by supaBOT."""
    try:
        return analyze_with_supabot(parsed, history=history)
    except SupaBOTLLMError as exc:
        return {"error": str(exc), "error_type": "SUPABOT_GATEWAY"}
    except Exception as exc:
        return {"error": str(exc), "error_type": "ANALYZE_UNEXPECTED"}
