create table if not exists public.oi_exposure_snapshots (
  id bigint generated by default as identity primary key, captured_at timestamptz not null default now(),
  snapshot_id bigint references public.options_flow_snapshots(id) on delete cascade, contract text, dte numeric, future_price numeric,
  net_delta_exposure numeric, gross_delta_exposure numeric, net_gex numeric, call_gex_total numeric, put_gex_total numeric,
  gamma_flip numeric, call_wall numeric, put_wall numeric, payload jsonb not null default '{}'::jsonb);
create index if not exists oi_exposure_snapshots_captured_at_idx on public.oi_exposure_snapshots(captured_at desc);
create index if not exists oi_exposure_snapshots_contract_idx on public.oi_exposure_snapshots(contract,captured_at desc);
alter table public.oi_exposure_snapshots enable row level security;
create table if not exists public.oi_flow_events (
  id bigint generated by default as identity primary key, captured_at timestamptz not null default now(),
  snapshot_id bigint references public.options_flow_snapshots(id) on delete cascade, contract text, strike numeric,
  label text not null check (label in ('NEW_LONG','NEW_SHORT','SHORT_COVER','LONG_LIQUIDATION','UNKNOWN')),
  confidence numeric not null default 0 check (confidence between 0 and 1), delta_oi_call numeric, delta_oi_put numeric,
  evidence jsonb not null default '[]'::jsonb, limitations jsonb not null default '[]'::jsonb);
create index if not exists oi_flow_events_snapshot_idx on public.oi_flow_events(snapshot_id);
create index if not exists oi_flow_events_contract_time_idx on public.oi_flow_events(contract,captured_at desc);
alter table public.oi_flow_events enable row level security;
create table if not exists public.oi_migration_events (
  id bigint generated by default as identity primary key, captured_at timestamptz not null default now(),
  snapshot_id bigint references public.options_flow_snapshots(id) on delete cascade, contract text,
  side text not null check (side in ('call','put')), from_strike numeric, to_strike numeric, estimated_oi numeric,
  confidence text not null default 'low');
create index if not exists oi_migration_events_snapshot_idx on public.oi_migration_events(snapshot_id);
alter table public.oi_migration_events enable row level security;