create table if not exists public.dataset_versions (
  version text primary key,
  source text not null,
  created_at timestamptz not null default now(),
  source_file text,
  source_version text,
  checksum text,
  description text
);

-- Canonical options data model for Phase 4.
-- Prepared only. Do NOT treat this migration as applied until the target
-- Supabase project identity is verified.

create table if not exists public.raw_market_data (
  id bigint generated by default as identity primary key,
  source text not null,
  source_file text,
  source_version text not null,
  fetched_at timestamptz not null,
  payload jsonb not null,
  checksum text not null,
  dataset_version text not null references public.dataset_versions(version),
  created_at timestamptz not null default now()
);

create index if not exists raw_market_data_source_time_idx
  on public.raw_market_data(source, fetched_at desc);

create table if not exists public.instruments (
  id text primary key,
  symbol text not null,
  root text not null,
  exchange text not null,
  asset_class text not null,
  currency text,
  timezone text not null default 'UTC',
  created_at timestamptz not null default now(),
  unique(exchange, root, symbol)
);

create table if not exists public.futures (
  id text primary key,
  instrument_id text not null references public.instruments(id),
  contract_code text not null,
  root text not null,
  exchange text not null,
  expiration timestamptz,
  multiplier numeric,
  currency text,
  tick_size numeric,
  settlement_type text,
  unique(exchange, contract_code)
);

create table if not exists public.expirations (
  id text primary key,
  underlying text not null,
  expiry timestamptz not null,
  timezone text not null default 'UTC',
  bucket text not null default 'UNKNOWN',
  is_weekly boolean not null default false,
  is_monthly boolean not null default false,
  unique(underlying, expiry)
);

create table if not exists public.strikes (
  id text primary key,
  underlying text not null,
  strike numeric not null,
  unique(underlying, strike)
);

create table if not exists public.options (
  id text primary key,
  instrument_id text references public.instruments(id),
  future_id text references public.futures(id),
  expiration_id text not null references public.expirations(id),
  strike_id text not null references public.strikes(id),
  root text not null,
  underlying text not null,
  exchange text not null,
  option_type text not null check (option_type in ('CALL', 'PUT')),
  contract_code text not null,
  multiplier numeric,
  currency text,
  settlement_type text,
  source text not null,
  active_from timestamptz,
  active_to timestamptz,
  unique(exchange, contract_code),
  unique(expiration_id, strike_id, option_type, underlying)
);

create table if not exists public.option_quotes (
  id bigint generated by default as identity primary key,
  option_id text not null references public.options(id) on delete cascade,
  observation_time timestamptz not null,
  bid numeric,
  ask numeric,
  bid_size numeric,
  ask_size numeric,
  last numeric,
  implied_volatility numeric,
  delta numeric,
  gamma numeric,
  theta numeric,
  vega numeric,
  source text not null,
  dataset_version text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.option_trades (
  id bigint generated by default as identity primary key,
  option_id text not null references public.options(id) on delete cascade,
  trade_time timestamptz not null,
  price numeric,
  size numeric,
  premium numeric,
  observed_side text,
  source text not null,
  dataset_version text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.option_oi (
  id bigint generated by default as identity primary key,
  option_id text not null references public.options(id) on delete cascade,
  trade_date date not null,
  observation_time timestamptz not null,
  publication_time timestamptz,
  availability_time timestamptz,
  ingestion_time timestamptz not null default now(),
  calculation_time timestamptz,
  oi numeric not null check (oi >= 0),
  oi_change numeric,
  volume numeric,
  data_status text not null default 'VALID',
  source text not null,
  dataset_version text not null,
  created_at timestamptz not null default now(),
  check (
    availability_time is null
    or publication_time is null
    or availability_time >= publication_time
  )
);

create index if not exists option_oi_pit_idx
  on public.option_oi(option_id, availability_time, observation_time);

create index if not exists option_oi_trade_date_idx
  on public.option_oi(trade_date, availability_time);

create table if not exists public.greek_observations (
  id bigint generated by default as identity primary key,
  option_id text not null references public.options(id) on delete cascade,
  observation_time timestamptz not null,
  model text not null,
  calculation_version text not null,
  delta numeric,
  gamma numeric,
  theta numeric,
  vega numeric,
  implied_volatility numeric,
  iv_input_unit text not null,
  gamma_unit text not null,
  theta_unit text not null,
  vega_unit text not null,
  futures_price numeric not null,
  strike numeric not null,
  expiry_years numeric not null,
  risk_free_rate numeric not null default 0,
  dataset_version text not null
);

create table if not exists public.gex_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null,
  as_of timestamptz not null,
  dataset_version text not null,
  calculation_version text not null,
  expiry_scope text not null,
  sign_convention text not null,
  gamma_source text not null,
  contract_multiplier numeric not null,
  net_gex numeric,
  gross_gex numeric,
  gamma_flip numeric,
  call_wall numeric,
  put_wall numeric,
  data_status text not null default 'VALID',
  assumptions jsonb not null default '[]'::jsonb,
  payload jsonb not null default '{}'::jsonb
);

create index if not exists gex_snapshots_symbol_time_idx
  on public.gex_snapshots(symbol, as_of desc);

create table if not exists public.dex_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null,
  as_of timestamptz not null,
  dataset_version text not null,
  calculation_version text not null,
  net_dex numeric,
  gross_dex numeric,
  unit text not null,
  payload jsonb not null default '{}'::jsonb
);

create table if not exists public.market_states (
  id bigint generated by default as identity primary key,
  symbol text not null,
  as_of timestamptz not null,
  price numeric,
  oi numeric,
  oi_change numeric,
  gex numeric,
  dex numeric,
  iv numeric,
  realized_vol numeric,
  gamma_flip numeric,
  call_wall numeric,
  put_wall numeric,
  positioning_regime text not null,
  volatility_regime text not null,
  data_quality numeric not null check(data_quality >= 0 and data_quality <= 1),
  data_age_seconds numeric,
  data_status text not null,
  dataset_version text not null,
  calculation_version text not null,
  sign_convention text,
  gamma_source text,
  assumptions jsonb not null default '[]'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  positioning jsonb not null default '{}'::jsonb,
  unique(symbol, as_of, dataset_version, calculation_version)
);

alter table public.raw_market_data enable row level security;
alter table public.option_quotes enable row level security;
alter table public.option_trades enable row level security;
alter table public.instruments enable row level security;
alter table public.futures enable row level security;
alter table public.expirations enable row level security;
alter table public.strikes enable row level security;
alter table public.options enable row level security;
alter table public.option_oi enable row level security;
alter table public.greek_observations enable row level security;
alter table public.gex_snapshots enable row level security;
alter table public.dex_snapshots enable row level security;
alter table public.market_states enable row level security;
alter table public.dataset_versions enable row level security;

-- No anon/authenticated policies are created here. Server-side service access
-- must be used until the user-facing authorization model is implemented.
