-- Flow Intelligence v1: additive research/analysis backbone.
create table if not exists public.market_bars (
  id bigint generated by default as identity primary key,
  source text not null, instrument text not null, timeframe text not null,
  bar_time timestamptz not null, open numeric, high numeric, low numeric, close numeric,
  volume numeric, bid numeric, ask numeric, spread numeric, session text, timezone text,
  is_final boolean not null default true, provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(source, instrument, timeframe, bar_time)
);
create index if not exists market_bars_lookup_idx on public.market_bars(instrument, timeframe, bar_time desc);

create table if not exists public.market_state_snapshots (
  id bigint generated by default as identity primary key,
  as_of timestamptz not null, instrument text not null, state_version text not null,
  regime text, price_state jsonb not null default '{}'::jsonb,
  volatility_state jsonb not null default '{}'::jsonb, options_state jsonb not null default '{}'::jsonb,
  macro_state jsonb not null default '{}'::jsonb, microstructure_state jsonb not null default '{}'::jsonb,
  technical_state jsonb not null default '{}'::jsonb, path_state jsonb not null default '{}'::jsonb,
  evidence_refs jsonb not null default '[]'::jsonb, data_quality jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), unique(instrument, as_of, state_version)
);
create index if not exists market_state_snapshots_time_idx on public.market_state_snapshots(instrument, as_of desc);

create table if not exists public.structural_nodes (
  id bigint generated by default as identity primary key,
  snapshot_id bigint references public.market_state_snapshots(id) on delete cascade,
  instrument text not null, observed_at timestamptz not null, level numeric not null,
  futures_level numeric, cfd_level numeric, node_type text not null, role text, tier smallint,
  direction text, source text, expiry_scope jsonb not null default '{}'::jsonb,
  oi_context jsonb not null default '{}'::jsonb, risk_context jsonb not null default '{}'::jsonb,
  local_prominence numeric, distance_from_price numeric, volatility_distance numeric,
  state text not null default 'ACTIVE', evidence_refs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists structural_nodes_path_idx on public.structural_nodes(instrument, observed_at desc, direction, level);

create table if not exists public.structural_transitions (
  id bigint generated by default as identity primary key,
  from_node_id bigint not null references public.structural_nodes(id) on delete cascade,
  to_node_id bigint not null references public.structural_nodes(id) on delete cascade,
  condition_type text not null, condition jsonb not null default '{}'::jsonb,
  mechanism jsonb not null default '{}'::jsonb, priority text,
  state text not null default 'CONDITIONAL', evidence_refs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique(from_node_id, to_node_id, condition_type)
);

create table if not exists public.market_events (
  id bigint generated by default as identity primary key,
  event_time timestamptz not null, detected_at timestamptz not null default now(),
  instrument text, event_type text not null, source_type text not null, source_ref text,
  level numeric, direction text, magnitude numeric, status text not null default 'DETECTED',
  evidence jsonb not null default '{}'::jsonb, state_before jsonb not null default '{}'::jsonb,
  state_after jsonb not null default '{}'::jsonb, path_before jsonb not null default '{}'::jsonb,
  path_after jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index if not exists market_events_time_idx on public.market_events(instrument, event_time desc, event_type);

create table if not exists public.market_event_outcomes (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.market_events(id) on delete cascade,
  horizon_seconds integer not null, observed_at timestamptz, forward_return numeric,
  forward_range numeric, mfe numeric, mae numeric, next_node_hit boolean,
  next_node_id bigint references public.structural_nodes(id) on delete set null,
  time_to_next_node_seconds integer, realized_vol numeric, outcome_state text,
  metrics jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(),
  unique(event_id, horizon_seconds)
);
create index if not exists market_event_outcomes_event_idx on public.market_event_outcomes(event_id, horizon_seconds);

create table if not exists public.news_event_intelligence (
  id bigint generated by default as identity primary key,
  news_announcement_id bigint references public.news_announcements(id) on delete set null,
  news_event_id bigint references public.news_events(id) on delete set null,
  economic_event_id bigint references public.economic_events(id) on delete set null,
  observed_at timestamptz not null default now(), event_type text, canonical_topic text,
  entities jsonb not null default '[]'::jsonb, stance text, novelty text,
  surprise_raw numeric, surprise_z numeric, revision jsonb not null default '{}'::jsonb,
  transmission jsonb not null default '{}'::jsonb, market_response jsonb not null default '{}'::jsonb,
  market_state_impact jsonb not null default '{}'::jsonb, evidence_refs jsonb not null default '[]'::jsonb,
  epistemic_status text not null default 'UNKNOWN', model_version text, prompt_version text,
  status text not null default 'RAW', created_at timestamptz not null default now()
);
create index if not exists news_event_intelligence_time_idx on public.news_event_intelligence(observed_at desc, canonical_topic);

create table if not exists public.llm_analysis_runs (
  id bigint generated by default as identity primary key,
  request_id text not null, run_id text not null, task text not null, model text,
  prompt_version text not null, output_schema_version text not null, as_of timestamptz not null,
  input_refs jsonb not null default '[]'::jsonb, evidence_refs jsonb not null default '[]'::jsonb,
  data_status text not null, validation_status text not null default 'UNKNOWN',
  response jsonb, verifier_result jsonb not null default '{}'::jsonb, latency_ms integer,
  error_code text, created_at timestamptz not null default now(), unique(request_id)
);
create index if not exists llm_analysis_runs_task_time_idx on public.llm_analysis_runs(task, as_of desc);

create table if not exists public.market_event_documents (
  id bigint generated by default as identity primary key,
  event_id bigint references public.market_events(id) on delete cascade,
  document_type text not null, source text, title text, body text not null,
  published_at timestamptz, embedding extensions.vector(512),
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index if not exists market_event_documents_embedding_hnsw
  on public.market_event_documents using hnsw (embedding vector_cosine_ops);
create index if not exists market_event_documents_time_idx on public.market_event_documents(published_at desc);

alter table public.market_bars enable row level security;
alter table public.market_state_snapshots enable row level security;
alter table public.structural_nodes enable row level security;
alter table public.structural_transitions enable row level security;
alter table public.market_events enable row level security;
alter table public.market_event_outcomes enable row level security;
alter table public.news_event_intelligence enable row level security;
alter table public.llm_analysis_runs enable row level security;
alter table public.market_event_documents enable row level security;

revoke all on table public.market_bars, public.market_state_snapshots, public.structural_nodes,
  public.structural_transitions, public.market_events, public.market_event_outcomes,
  public.news_event_intelligence, public.llm_analysis_runs, public.market_event_documents
  from anon, authenticated;

grant select, insert, update, delete on table public.market_bars, public.market_state_snapshots,
  public.structural_nodes, public.structural_transitions, public.market_events,
  public.market_event_outcomes, public.news_event_intelligence, public.llm_analysis_runs,
  public.market_event_documents to service_role;
