create table if not exists public.oi_core_news_items (
  news_id text primary key,
  headline text not null,
  source text not null,
  url text not null,
  published_at timestamptz not null,
  detected_at timestamptz not null,
  event_time timestamptz,
  language text not null default 'en',
  category text not null default 'UNKNOWN',
  entities jsonb not null default '[]'::jsonb,
  assets jsonb not null default '[]'::jsonb,
  severity text not null default 'MEDIUM',
  status text not null default 'PENDING',
  provenance_id text,
  created_at timestamptz not null default now()
);

create index if not exists oi_core_news_published_idx
  on public.oi_core_news_items(published_at desc);

create table if not exists public.oi_core_story_clusters (
  cluster_id text primary key,
  canonical_headline text not null,
  news_ids jsonb not null default '[]'::jsonb,
  source_count integer not null default 0 check(source_count >= 0),
  first_published_at timestamptz not null,
  last_published_at timestamptz not null,
  official_source boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.oi_core_market_confirmations (
  id bigint generated by default as identity primary key,
  cluster_id text not null references public.oi_core_story_clusters(cluster_id) on delete cascade,
  confirmed boolean not null,
  score numeric not null check(score >= 0 and score <= 1),
  price_reaction numeric,
  volatility_reaction numeric,
  oi_change numeric,
  gex_change numeric,
  dex_change numeric,
  market_state_changed boolean not null default false,
  evidence jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists oi_core_confirmation_cluster_idx
  on public.oi_core_market_confirmations(cluster_id, created_at desc);

create table if not exists public.oi_core_news_impacts (
  news_id text not null references public.oi_core_news_items(news_id) on delete cascade,
  cluster_id text not null references public.oi_core_story_clusters(cluster_id) on delete cascade,
  severity text not null,
  confidence numeric not null check(confidence >= 0 and confidence <= 1),
  assets jsonb not null default '[]'::jsonb,
  direction text not null,
  horizon text not null default 'UNKNOWN',
  impact_reason jsonb not null default '[]'::jsonb,
  source_count integer not null default 0,
  official_source boolean not null default false,
  market_confirmation_id bigint references public.oi_core_market_confirmations(id),
  model_version text not null,
  created_at timestamptz not null default now(),
  primary key(news_id, cluster_id)
);

create table if not exists public.oi_core_market_analyses (
  id bigint generated by default as identity primary key,
  symbol text not null,
  as_of timestamptz not null,
  market_context text not null,
  what_changed text not null,
  why_it_matters text not null,
  key_levels jsonb not null default '[]'::jsonb,
  risk_factors jsonb not null default '[]'::jsonb,
  uncertainties jsonb not null default '[]'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  confidence numeric not null check(confidence >= 0 and confidence <= 1),
  generated_at timestamptz not null default now(),
  model_version text not null,
  dataset_version text not null,
  calculation_version text not null
);

create index if not exists oi_core_market_analyses_symbol_time_idx
  on public.oi_core_market_analyses(symbol, as_of desc);

create table if not exists public.oi_core_scenario_plans (
  scenario_id text primary key,
  market text not null,
  directional_bias text not null,
  trigger jsonb not null default '[]'::jsonb,
  confirmation jsonb not null default '[]'::jsonb,
  invalidation jsonb not null default '[]'::jsonb,
  key_levels jsonb not null default '[]'::jsonb,
  risk_factors jsonb not null default '[]'::jsonb,
  supporting_evidence jsonb not null default '[]'::jsonb,
  contradicting_evidence jsonb not null default '[]'::jsonb,
  confidence numeric not null check(confidence >= 0 and confidence <= 1),
  valid_until timestamptz not null,
  version text not null,
  status text not null default 'ACTIVE' check(status in ('ACTIVE','UPDATED','INVALIDATED','EXPIRED')),
  created_at timestamptz not null default now()
);

create index if not exists oi_core_scenario_market_time_idx
  on public.oi_core_scenario_plans(market, created_at desc);

alter table public.oi_core_news_items enable row level security;
alter table public.oi_core_story_clusters enable row level security;
alter table public.oi_core_market_confirmations enable row level security;
alter table public.oi_core_news_impacts enable row level security;
alter table public.oi_core_market_analyses enable row level security;
alter table public.oi_core_scenario_plans enable row level security;

revoke all on table public.oi_core_news_items, public.oi_core_story_clusters,
  public.oi_core_market_confirmations, public.oi_core_news_impacts,
  public.oi_core_market_analyses, public.oi_core_scenario_plans
  from anon, authenticated;
